### PR TITLE
adds data for Jun 16th

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by aidanheerdegen** [comment]
Not a good schema IMO

**Review by adele-morrison — APPROVED** [review]
Looks good! I'm not sure this really needs a review though...

**Comment by navidcy** [comment]
@aidanheerdegen "schema"? are you talking about form of data... of course, there is a lot of room for improvement.

@adele157, people might argue that I was manipulating data. :)

**Comment by aidanheerdegen** [comment]
I have made an issue ;)

https://github.com/ClimateFluidPhysics-ANU/Office-on-Wednesdays-correlations-paper/issues/2

**Pull request merged**
